### ISSUE TITLE
Publish to NPM! :)

### ISSUE THREAD

**Issue by alexweber** [fny/gulp-firebase-bolt-compiler#1]
Does this thing work? Publish it please! :)  Was about to write my own but found this... thanks!

**Comment by fny** [comment]
Can't believe I missed this issue! (Must've been drowned in a pile of others. Yes it works, and I'd be glad to publish it to NPM.

**Comment by fny** [comment]
[Published](https://www.npmjs.com/package/gulp-firebase-bolt-compiler)! Once again, apologies.
